### ISSUE TITLE
Document design guidelines

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#117]
### Todo
- [x] Move documentation from Figma to the microsite
- [x] Clean up design docs #170 @heatherlarsen 
  - [x] Re-organize docs into logical sections & clean up bullet formatting (MVP)
  - [x] Add new docs from Figma (MVP)
- [x] Finalize the documentation @dizzyup 
- ~~Remove documentation from figma and instead link out to the microsite~~
- ~~Mimic [Figma Docs](https://www.figma.com/file/TLnoT5AYQfy3tZ0H68BgOr/Flight-Icons?node-id=636%3A137) as much as possible (to be completed with another issue during polish)~~

**Comment by heatherlarsen** [comment]
Decided to leave documentation in Figma to better aid Designers during the creation process. We've agreed to make it a part of the process that when one source gets update, so does the other. This is likely just to be necessary for Flight icons and not future components. @Dhaulagiri @dizzyup

**Comment by Dhaulagiri** [comment]
👍  I think we can close this issue

**Comment by heatherlarsen** [comment]
@Dhaulagiri I was actually going to use this for the updates that need to be made once @MelSumner merges #170. @dizzyup also has more design docs he's working on in Figma to beef up some of the content. Do you want me to create new issues for those?
