### ISSUE TITLE
Export script (Node version) - Syncing

### ISSUE THREAD

**Issue by didoo** [hashicorp/flight#155]
#### Description
This is the first part (the "syncing") of the new Node.js version of the "Figma to Flight" export script.
What it does is to download the SVG assets in a specific folder, overriding the default file names (Figma uses the variant name for it, and that would be `Size=16` or `Size=24`)

#### Expected logic
This is an outline of what we intend to implement

```
INIT
- get a few options from the command line arguments [TBD, it depends on how we want to use the script]
- read a configuration file to get the list of files/pages/frames we want to sync from

SYNC
- loop over the files, pages and frames to get a list of all the icons (Figma "components") we need to export
- loop over the list of assets we need to process and for each one of them
  - get all the relevant meta-data about the asset
    - component set name (will be used later to save the SVGs with a more meaningful filename)
    - size
    - description (used to provide alternative search terms)
  - download the asset in SVG format and rename it accordingly (if in the future we may need different formats (eg. PNG for email) we'll modify the script accordingly)
- save a "catalog.json" file containing the list of assets and their relevant metadata
```

#### Things to consider/keep in mind

- We intend to use an open source library (https://github.com/marcomontalbano/figma-export or as a fallback https://github.com/tsimenis/figma-export-icons). If these libraries will not meet our needs, we'll implement a custom script.
- To fix the problem with the naming of the exported files, we'll use the REST API to retrieve the icons metadata (parent name, size, description etc). At the moment of writing, is not yet clear how this will work (and if it will work at all!): it depends on the library we're using, we need to pass an ID for the export of the Figma component so we can associate it with the metadata and rename the exported file to be meaningful).
- We'll try to implement the script as agnostic as possible on the exported format (reason: for now we use SVG, but in the future we may also need other formats, eg. PNGs for emails, PDF for slide decks, etc).
- At the moment we'll use the folder structure proposed in #28. It will be easy to change later, when it's finalised.

#### Tasks
- [x] Setup the script so that can be run via CLI (package.json + initial code)
- [x] Build a working prototype to test the existing open source libraries
- [x] Check if it's possible to require a specific ID/icon (so later we can change its name using the metadata)
- [x] If it's possible, add the logic to the script to rename the downloaded assets (and avoid conflicts/overwrites at runtime)
- [ ] ~~If it's **not** possible, build a custom script to export the assets ourselves.~~
- [x] Add logic to create the `catalog.json` file
- [x] Add README file (similar to the GO one)
- [ ] Remove the "export-go" folder
- [ ] Run the "sync" script to generate the "src" assets

Notice: since it is not dependant on the comments of #28 we can start to work on it straightaway.
