### ISSUE TITLE
Address TODO's on design.hbs

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#369]
In this instance, it seemed to make more sense to file an issue vs. removing them, since I wasn't 100% sure of the TODO yet from a quick look.

- [ ] https://github.com/hashicorp/flight/blob/main/website/app/templates/design.hbs#L76
- [ ] https://github.com/hashicorp/flight/blob/main/website/app/templates/design.hbs#L196
- [ ] https://github.com/hashicorp/flight/blob/main/website/app/templates/design.hbs#L398
- [ ] https://github.com/hashicorp/flight/blob/main/website/app/templates/design.hbs#L646
- [ ] https://github.com/hashicorp/flight/blob/main/website/app/templates/design.hbs#L678
- [ ] https://github.com/hashicorp/flight/blob/main/website/app/templates/design.hbs#L730

I wasn't sure why we were using images from Figma. Perhaps we could explore Figma Embed on Flight, and continue to use an image on design-system-components while is still in work? 

- Comments I had about the screenshot images from Figma:
https://github.com/hashicorp/design-system-components/issues/117#issuecomment-1007066156 and https://github.com/hashicorp/design-system-components/issues/117#issuecomment-1007882682

**Comment by amyrlam** [comment]
closing issues related to flight docs as won't do
